package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JisanTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void jisan() throws InterruptedException {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1280, 800));
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("error_user");
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        Thread.sleep(2000);

        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        Thread.sleep(2000);
//        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
//        {
//            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector(".shopping_cart_badge")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("jisan");
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
        Thread.sleep(2000);
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
        Thread.sleep(2000);
    }
}
